apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-sa
  namespace: llm
  labels:
    app: open-webui
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-sa
  namespace: llm
  labels:
    app: ollama
automountServiceAccountToken: false
