import { useState, useEffect } from 'react';
import type { RecommendationResponse, HealthResponse } from './types';
import './App.css';

function App() {
  const [temperature, setTemperature] = useState(0.2);
  const [topP, setTopP] = useState(0.9);
  const [model, setModel] = useState('llama3.2');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [response, setResponse] = useState<RecommendationResponse | null>(null);
  const [health, setHealth] = useState<HealthResponse | null>(null);

  // Check backend health on mount
  useEffect(() => {
    fetch('/health')
      .then((res) => res.json())
      .then((data) => setHealth(data))
      .catch((err) => console.error('Health check failed:', err));
  }, []);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);

    try {
      const res = await fetch('/api/recommendations', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          temperature,
          top_p: topP,
          model,
        }),
      });

      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error || 'Failed to generate recommendations');
      }

      const data: RecommendationResponse = await res.json();
      setResponse(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="app">
      <header className="header">
        <h1>🍽️ Restaurant Operations Dashboard</h1>
        <p className="subtitle">LLM-Powered Insights via Ollama</p>
        {health && (
          <div className={`health-badge ${health.ollama.connected ? 'connected' : 'disconnected'}`}>
            {health.ollama.connected ? '● Connected to Ollama' : '○ Ollama Disconnected'}
          </div>
        )}
      </header>

      <main className="main">
        <section className="controls">
          <h2>Knobs & Parameters</h2>
          <div className="knob-grid">
            <div className="knob">
              <label htmlFor="model">Model</label>
              <input
                id="model"
                type="text"
                value={model}
                onChange={(e) => setModel(e.target.value)}
                placeholder="e.g., llama3.2"
              />
              <small>Model name in Ollama</small>
            </div>

            <div className="knob">
              <label htmlFor="temperature">
                Temperature: <strong>{temperature.toFixed(2)}</strong>
              </label>
              <input
                id="temperature"
                type="range"
                min="0"
                max="2"
                step="0.1"
                value={temperature}
                onChange={(e) => setTemperature(parseFloat(e.target.value))}
              />
              <small>0.0 = deterministic, 1.0+ = creative</small>
            </div>

            <div className="knob">
              <label htmlFor="topP">
                Top-p: <strong>{topP.toFixed(2)}</strong>
              </label>
              <input
                id="topP"
                type="range"
                min="0"
                max="1"
                step="0.05"
                value={topP}
                onChange={(e) => setTopP(parseFloat(e.target.value))}
              />
              <small>Nucleus sampling threshold</small>
            </div>
          </div>

          <button
            className="generate-btn"
            onClick={handleGenerate}
            disabled={loading || !health?.ollama.connected}
          >
            {loading ? 'Generating...' : 'Generate Recommendations'}
          </button>

          {error && <div className="error">Error: {error}</div>}
        </section>

        {response && (
          <section className="results">
            <div className="result-card">
              <h3>📊 Summary</h3>
              <div className="content">{formatText(response.summary)}</div>
            </div>

            <div className="result-card">
              <h3>💡 Recommendations</h3>
              <div className="content">{formatText(response.recommendations)}</div>
            </div>

            <div className="result-card">
              <h3>🔔 Staff Notifications</h3>
              <div className="content">{formatText(response.staff_notifications)}</div>
            </div>

            <div className="metadata">
              <small>
                Generated by <strong>{response.metadata.model}</strong> •
                temp={response.metadata.temperature} • top_p={response.metadata.top_p} •
                {new Date(response.metadata.timestamp).toLocaleTimeString()}
              </small>
            </div>
          </section>
        )}

        <section className="info">
          <h3>ℹ️ How This Works</h3>
          <ul>
            <li>
              <strong>Backend</strong> sends sample orders + your parameters to Ollama
            </li>
            <li>
              <strong>Ollama</strong> (running in Kubernetes) generates responses using the selected model
            </li>
            <li>
              <strong>Frontend</strong> displays the parsed summary, recommendations, and notifications
            </li>
            <li>
              <strong>Iterate</strong> by adjusting temperature/top_p to see how responses change
            </li>
            <li>
              <strong>Freeze</strong> final behavior into a Modelfile when satisfied (see README)
            </li>
          </ul>
        </section>
      </main>
    </div>
  );
}

function formatText(text: string): JSX.Element {
  return (
    <>
      {text.split('\n').map((line, i) => (
        <p key={i}>{line}</p>
      ))}
    </>
  );
}

export default App;
